  blynk_server:
    container_name: blynk_server
    restart: unless-stopped
    ports:
      - 8180:8080
      - 8441:8441
      - 9443:9443
    volumes:
      - ./volumes/blynk_server/data:/data
      - ./.templates/blynk_server/server.properties:/config/server.properties
      - ./.templates/blynk_server/mail.properties:/blynk/mail.properties
    image: 'maxbanton/blynk-server:latest'
